gtkdocize: Fix GTK_DOC_CHECK argument handling
After commit 1401aebc625dd1c7c39457d3455dce3019ded0be, any extra
arguments passed to gtkdocize by GTK_DOC_CHECK in configure.ac were
ignored. This broke because the arguments to GTK_DOC_CHECK are injected
into the argument for gtkdocize, but the rearrangement to add --srcdir
support pushed the injection down to after where the arguments were
parsed.

Fix the argument handling by checking for a --srcdir agument (and for
GTK_DOC_CHECK) before parsing other arguments.

https://bugzilla.gnome.org/show_bug.cgi?id=707426

diff --git a/gtkdocize.in b/gtkdocize.in
--- a/gtkdocize.in
+++ b/gtkdocize.in
@@ -19,32 +19,11 @@ flavour=legacy
 usage="\
 usage: $progname [ --copy ] [ --docdir DIR ] [ --flavour {legacy|legacy-flat|no-tmpl|no-tmpl-flat} ] [ --srcdir DIR ]"
 
+# Find the srcdir early (and ignore a srcdir set in configure).
+# https://bugzilla.gnome.org/show_bug.cgi?id=707426
+args="$*"
 while test $# -gt 0; do
-  #echo >&2 "DEBUG: parsing args [$1]";
   case "$1" in
-  --help)
-    echo "$usage"
-    exit 0 ;;
-  --version)
-    echo "$PROGRAM ($PACKAGE) $VERSION"
-    exit 0 ;;
-  --copy)
-    copy=yes
-    shift ;;
-  --docdir)
-    shift
-    docdir="$1"
-    shift ;;
-  --docdir=*)
-    docdir=`expr "X$1" : '[^=]*=\(.*\)'`
-    shift ;;
-  --flavour)
-    shift
-    flavour="$1"
-    shift ;;
-  --flavour=*)
-    flavour=`expr "X$1" : '[^=]*=\(.*\)'`
-    shift ;;
   --srcdir)
     shift
     srcdir="$1"
@@ -52,34 +31,11 @@ while test $# -gt 0; do
   --srcdir=*)
     srcdir=`expr "X$1" : '[^=]*=\(.*\)'`
     shift ;;
-  -*)
-    echo "$progname: unrecognised option '$1'" 1>&2
-    echo "$usage" 1>&2
-    exit 1 ;;
   *)
-    echo "$progname: too many arguments" 1>&2
-    echo "$usage" 1>&2
-    exit 1 ;;
+    shift ;;
   esac
 done
-
-case "$flavour" in
-  legacy*)
-    ;;
-  legacy-flat*)
-    makefile=gtk-doc.flat.make
-    ;;
-  no-tmpl*)
-    makefile=gtk-doc.notmpl.make
-    ;;
-  no-tmpl-flat*)
-    makefile=gtk-doc.notmpl-flat.make
-    ;;
-  *)
-    echo "$progname: invalid value for --flavour" 1>&2
-    echo "$usage" 1>&2
-    exit 1 ;;
-esac
+set - $args
 
 # assume working directory if srcdir is not set
 test "$srcdir" || srcdir=.
@@ -113,6 +69,68 @@ if test $no_configure_found -eq 0; then
     no_gtk_doc_check_found=1;
   fi
 fi
+
+while test $# -gt 0; do
+  #echo >&2 "DEBUG: parsing args [$1]";
+  case "$1" in
+  --help)
+    echo "$usage"
+    exit 0 ;;
+  --version)
+    echo "$PROGRAM ($PACKAGE) $VERSION"
+    exit 0 ;;
+  --copy)
+    copy=yes
+    shift ;;
+  --docdir)
+    shift
+    docdir="$1"
+    shift ;;
+  --docdir=*)
+    docdir=`expr "X$1" : '[^=]*=\(.*\)'`
+    shift ;;
+  --flavour)
+    shift
+    flavour="$1"
+    shift ;;
+  --flavour=*)
+    flavour=`expr "X$1" : '[^=]*=\(.*\)'`
+    shift ;;
+  --srcdir)
+    shift
+    # srcdir was set earlier.
+    shift ;;
+  --srcdir=*)
+    # srcdir was set earlier.
+    shift ;;
+  -*)
+    echo "$progname: unrecognised option '$1'" 1>&2
+    echo "$usage" 1>&2
+    exit 1 ;;
+  *)
+    echo "$progname: too many arguments" 1>&2
+    echo "$usage" 1>&2
+    exit 1 ;;
+  esac
+done
+
+case "$flavour" in
+  legacy*)
+    ;;
+  legacy-flat*)
+    makefile=gtk-doc.flat.make
+    ;;
+  no-tmpl*)
+    makefile=gtk-doc.notmpl.make
+    ;;
+  no-tmpl-flat*)
+    makefile=gtk-doc.notmpl-flat.make
+    ;;
+  *)
+    echo "$progname: invalid value for --flavour" 1>&2
+    echo "$usage" 1>&2
+    exit 1 ;;
+esac
 
 if test $no_configure_found -eq 1; then
   echo "$progname: neither configure.ac nor configure.in exist" 1>&2
